### ISSUE TITLE
can't ssh master pi after applying metallb-config.yaml

### ISSUE THREAD

**Issue by ilanKushnir** [mortylabs/kubernetes#2]
when I run the `kubectl apply -f metallb-config.yaml` command in [this stage](https://github.com/mortylabs/kubernetes#installation---metallb-load-balancer), I'm getting disconnected from the pi and can't reconnect via SSH again

my configuration is:
```
apiVersion: v1
kind: ConfigMap
metadata:
    namespace: metallb-system
    name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 10.100.102.50-10.100.102.51
```

and mi PIs are RPI 4 (8GB):
* rpi-01-master: 10.100.102.50
* rpi-02-worker: 10.100.102.51

thanks a lot for the config! it almost worked but I'm missing something
can you please tell me where is my mistake here?
thanks!!!
